apiVersion: v1
kind: Service
metadata:
  name: app1-service              # Same name used in Ingress
spec:
  type: ClusterIP                # Internal service
  selector:
    app: app1                    # Connects to pods with this label
  ports:
    - port: 80                   # Service port
      targetPort: 80             # Pod container port
